import { appName } from "../app/services/appName";
export const routes = {
  tabNavigator: "Tabs",
  homeScreen: "Home",
  searchScreen: "Search",
  newListingScreen: "New Listing",
  chatListScreen: "Chats",
  accountScreen: "Account",
  listingDetailScreen: "Listing Detail",
  sendEmailScreen: "Send Email",
  contactUsScreen: "Contact us",
  reportScreen: "Report",
  chatScreen: "Chat",
  selectLocationScreen: "Location",
  settingsScreen: "Settings",
  loginScreen: "Log In",
  signUpScreen: "Sign Up",
  myListingsScreen: "My Listings",
  myMembershipScreen: "My Membership",
  favouriteScreen: "Favourite",
  myProfileScreen: "My Profile",
  fAQScreen: "FAQ",
  howToSellFastScreen: "How To Sell Fast",
  moreScreen: "More",
  aboutAppScreen: appName,
  selectcategoryScreen: "Select category",
  privacyPolicyScreen: "Privacy Policy",
  thirdPartyLicensesScreen: "Licenses",
  Screen: "Licenses",
  tnCScreen: "TnC",
  editPersonalDetailScreen: "Edit Personal Detail",
  editListingScreen: "Edit Listing",
  storeDetailsScreen: "Store Details",
  storeMoreDetailsScreen: "More Details Store",
  allStoresScreen: "Stores",
  myStoreScreen: "My Store Settings",
  membershipsScreen: "Membership Packages",
  paymentMethodScreen: "Payment Method",
  promoteScreen: "Promote Ad",
  paymentsScreen: "Payments",
  paymentDetailScreen: "Payment Detail",
};
